/read includes files recursively when given a directory
paul-gauthier/aider pull request #1061
Opened 2024-08-12 03:18 UTC by jbellis

This is useful when you want to give the LLM documentation about a library or framework that it is unfamiliar with.

2024-08-16 00:41 UTC, Jckwind commented
looks great!

2024-08-16 01:35 UTC, Jckwind requested changes
good idea and functionality, you'll probably want to incorporate .aiderignore files. would look like this:
`# If it's a directory, add all files in the directory
        for root, _, files in os.walk(abs_path):
            for file in files:
                abs_file_path = os.path.join(root, file)
                if self.coder.repo and self.coder.repo.ignored_file(abs_file_path):
                    # optional: log the ignored file
                    # self.io.tool_error(f"Skipping {abs_file_path} that matches aiderignore spec.")
                    continue
                self.coder.abs_read_only_fnames.add(abs_file_path)
                self.io.tool_output(f"Added {abs_file_path} to read-only files.")`

2024-08-19 17:08 UTC, paul-gauthier commented
Thanks for putting together this PR. Are you able to add @Jckwind 's suggested changes for the aider ignore file and look into the failing tests so I can merge this?

2024-08-23 21:21 UTC, jbellis commented
Added the aiderignore integration.

It's not clear to me what's going on with the tests.  Apparently there are two failures in CI in test_main, but test_main passes consistently for me locally.

2024-09-10 20:03 UTC, paul-gauthier commented
Thanks for this PR, I implemented it since there were merge conflicts.

2024-09-10 20:03 UTC, closed without merging