logs interactions with the LLM in response to user interactions
paul-gauthier/aider pull request #631
Opened 2024-05-31 14:55 UTC by daniel-vainsencher

Add a new file .aider.llm.history. 

The goal is to help see exactly what aider is sending to the LLM, and what exactly the LLM is responding, as a way to understand, for example, what went wrong retroactively.

This overlaps with --verbose mode, which otherwise outputs, among things, approximately this content, but gets in the way of regular interaction and thus is usually off.

Also along the way did a small refactoring to separate formatting from i/o.

Propose to do before landing:
- [ ] Add command line switch/configuration items to turn this on/off (I would default to on, but that might be atypical usage)

2024-06-07 14:49 UTC, daniel-vainsencher commented
@paul-gauthier I noticed today that other `.aider*` history files were configurable and written through InputOutput. I've updated this code accordingly and also rebased on current main. Is this change desirable? any other updates needed?

2024-06-11 18:43 UTC, paul-gauthier requested changes
This looks great to me. I've often thought about adding something like this.

2024-06-11 18:43 UTC, paul-gauthier commented on aider/args.py
> +        default=".aider.llm.history",
I think we want to default this to None? Most users won't want to be logging this level of detail.

2024-06-11 18:43 UTC, paul-gauthier commented on aider/coders/base_coder.py
> +        import datetime
These imports should go at the top.

2024-06-12 22:34 UTC, daniel-vainsencher commented
Addressed comments, fixed merge conflicts, tests pass locally.

2024-06-17 20:58 UTC, merged

2024-06-17 20:58 UTC, paul-gauthier commented
Great, thanks!